const Tour = require('../models/tourModels');

// Code outside request handlers (like the one below) are executed only once, when the application is first
// started on the server. So code outside request handlers are not a part if event loop.
// const tours = JSON.parse(
//   fs.readFileSync(`${__dirname}/../dev-data/data/tours-simple.json`),
// );

exports.getAllTours = async (req, res) => {
  try {
    const queryParams = { ...req.query };
    // Remove these params from the object.
    const excludedFields = ['page', 'sort', 'limit', 'fields'];
    excludedFields.forEach((field) => delete queryParams[field]);

    let queryStr = JSON.stringify(queryParams);
    // Replace all occurence of gte, gt... with $gte, $gt...
    queryStr = queryStr.replace(/\b(gte|gt|lte|lt)\b/g, (match) => `$${match}`);

    // If you do not pass any object to find, it will return all the documents in the collection.
    // Build query.
    let query = Tour.find(JSON.parse(queryStr));

    if (req.query.sort) {
      const sortParam = req.query.sort.split(',').join(' ');
      query = query.sort(sortParam);
    } else {
      // If there is no sort param in the api, by deafult sort by this field.
      query = query.sort('-createdAt');
    }

    // Execute query.
    const tours = await query;

    // find methods returns an object of type query.
    // find method returns a query object so that you can chain it with more queries.
    // Tour.find().where('duration').equals(5).where('difficulty').equals('easy');

    res.status(200).json({
      // This is coming from middleware. i.e app level middleware.
      requestedTime: req.requestTime,
      status: 'success',
      data: {
        tours,
      },
    });
  } catch (error) {
    res.status(404).json({
      status: 'fail',
      message: error,
    });
  }
};

exports.getTour = async (req, res) => {
  try {
    // This is similar to Tour.findOne({_id: req.params.id})
    // _id is the autogenerated field by mongo in the document
    const tour = await Tour.findById(req.params.id);
    res.status(200).json({
      status: 'success',
      data: {
        tour,
      },
    });
  } catch (error) {
    res.status(404).json({
      status: 'fail',
      message: error,
    });
  }
};

exports.createTour = async (req, res) => {
  try {
    const tour = await Tour.create(req.body);
    res.status(201).json({
      status: 'success',
      data: {
        tour,
      },
    });
  } catch (error) {
    res.status(400).json({
      status: 'fail',
      message: 'Invalid data sent',
    });
  }
};

exports.updateTour = async (req, res) => {
  try {
    const tour = await Tour.findByIdAndUpdate(req.params.id, req.body, {
      new: true, // Return the new updated document
      runValidators: true,
    });
    res.status(200).json({
      status: 'success',
      data: {
        tour,
      },
    });
  } catch (error) {
    res.status(400).json({
      status: 'fail',
      message: 'Invalid data sent',
    });
  }
};

exports.deleteTour = async (req, res) => {
  try {
    await Tour.findByIdAndDelete(req.params.id);
    res.status(204).json({
      status: 'success',
      data: null,
    });
  } catch (error) {
    res.status(400).json({
      status: 'fail',
      message: 'Invalid data sent',
    });
  }
};
